### PR TITLE
Fixes and Features

### PR DESCRIPTION
**Pull request by EgorFront**
### Introduction
I am very impressed with this project

I dont have much experience in openSource, but i really want to help this project
So i tried to use it in my project, but i found some bugs

**Important note**
I've tried to commit my changes, but i had error on git hooks lint-stage
I have no clue why it's happened, so I **disabled precommits hooks** in `husky.config.js`

Also I had problem with jest snapshots (i dont have any expirience with it)

I expect that u will check my changes, enable hooks, maybe fix tests. So I hope i did everything correct

### Fixes
- Fix: Syntax Error Bad character escape sequence on Windows [commit](https://github.com/Calvin-LL/vue-image-modernizer/commit/e5ec30ff8185b5f677406375ef583d393fe98e51)
- Fix(core): parseElementLevelOptions [commit](https://github.com/Calvin-LL/vue-image-modernizer/commit/04f1cb5b098d92c546928e294ad6b060eb201c46)
The bug was in regular expression, when passing both array options (sizes & imageFormats)

### Features
- Add avif support [commit](https://github.com/Calvin-LL/vue-image-modernizer/commit/77a59112ad693573f31016235d5cb72e2fc1867f)
- Feat(core-vue2 & core-vue3): Add copying `sizes` attr [commit](https://github.com/Calvin-LL/vue-image-modernizer/commit/ecf1ca44a22a8b58d8e71956267ba7af3ae041ae)
I added this for better control responsiveness on mobile when img transforms into picture

### CODE REVIEW

**Comment by Calvin-LL** [comment]
Thanks for the pr. I'll take a look this weekend. If you want to skip the hooks, try adding `--no-verify` when running `git commit` and `git push` (see https://stackoverflow.com/a/63948896/15101364)

**Comment by EgorFront** [comment]
I would like to use this repository as a dependency
When do you plan to release this changes?

**Comment by Calvin-LL** [comment]
> I would like to use this repository as a dependency
> When do you plan to release this changes?

Sorry for the delay, I'll release it within 24 hours.

**Comment by Calvin-LL** [comment]
> I would like to use this repository as a dependency
> When do you plan to release this changes?

released

**Pull request merged**
